/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118425-g33679f5325-20250205"
#endif /* AVUTIL_FFVERSION_H */
